FROM alpine:3.20.2
# ⬆️ This line is fetching from the public image: alpine:latest from the public docker hub

# ⬇️ Add base working directory, all follow up commands will execute from this base path
WORKDIR /app
